import { reports, users } from "@/lib/data";
import { notFound } from "next/navigation";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar";
import { Separator } from "@/components/ui/separator";
import { Checkbox } from "@/components/ui/checkbox";
import { Label } from "@/components/ui/label";
import { Button } from "@/components/ui/button";
import { Bot, Calendar, User, Shield, Tag, FileText, CheckCircle, Hourglass, XCircle, UserX } from "lucide-react";
import { format, parseISO } from "date-fns";

export default function ReportDetailPage({ params }: { params: { id: string } }) {
  const report = reports.find((r) => r.id === params.id);

  if (!report) {
    notFound();
  }

  const statusIcons = {
    "New": <FileText className="h-4 w-4" />,
    "In Progress": <Hourglass className="h-4 w-4" />,
    "Resolved": <CheckCircle className="h-4 w-4" />,
    "Dismissed": <XCircle className="h-4 w-4" />,
  };
  const severityIcons = {
    "Low": <Shield className="h-4 w-4" />,
    "Medium": <Shield className="h-4 w-4" />,
    "High": <Shield className="h-4 w-4 text-destructive" />,
  };

  return (
    <div className="mx-auto max-w-5xl space-y-6">
      <div>
        <Badge variant={report.severity === 'High' ? 'destructive' : 'secondary'} className="capitalize mb-2">{report.severity} Severity</Badge>
        <h1 className="font-headline text-4xl font-bold">{report.title}</h1>
      </div>

      <div className="grid md:grid-cols-3 gap-6">
        <div className="md:col-span-2 space-y-6">
          <Card>
            <CardHeader>
              <CardTitle>Report Details</CardTitle>
            </CardHeader>
            <CardContent className="space-y-4">
              <p className="text-foreground leading-relaxed whitespace-pre-wrap">
                {report.content}
              </p>
            </CardContent>
          </Card>

          <Card className="bg-primary/5 border-primary/20">
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <Bot className="h-6 w-6 text-primary" />
                AI-Powered Analysis
              </CardTitle>
              <CardDescription>
                Automated summary and risk assessment generated by Integrity Beacon AI.
              </CardDescription>
            </CardHeader>
            <CardContent className="space-y-6">
              <div>
                <h3 className="font-semibold mb-2">Summary</h3>
                <p className="text-sm text-muted-foreground">{report.aiSummary}</p>
              </div>
              <div>
                <h3 className="font-semibold mb-2">Risk Assessment</h3>
                <p className="text-sm text-muted-foreground">{report.aiRiskAssessment}</p>
              </div>
               <div>
                <h3 className="font-semibold mb-2">Reasoning</h3>
                <p className="text-sm text-muted-foreground">{report.aiReasoning}</p>
              </div>
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle>Suggested Investigation Steps</CardTitle>
              <CardDescription>AI-recommended actions to begin the investigation.</CardDescription>
            </CardHeader>
            <CardContent className="space-y-4">
              {report.aiSuggestedSteps?.map((step, index) => (
                <div key={index} className="flex items-center space-x-3">
                  <Checkbox id={`step-${index}`} />
                  <Label htmlFor={`step-${index}`} className="text-sm font-medium leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70">
                    {step}
                  </Label>
                </div>
              ))}
            </CardContent>
          </Card>
        </div>

        <div className="space-y-6">
          <Card>
            <CardHeader>
              <CardTitle>Case Information</CardTitle>
            </CardHeader>
            <CardContent className="space-y-4 text-sm">
              <div className="flex items-center justify-between">
                <span className="text-muted-foreground flex items-center gap-2"><FileText className="h-4 w-4"/>Status</span>
                <Badge variant="outline" className="capitalize">{report.status}</Badge>
              </div>
              <div className="flex items-center justify-between">
                <span className="text-muted-foreground flex items-center gap-2"><Calendar className="h-4 w-4"/>Submitted</span>
                <span>{format(parseISO(report.submittedAt), "PPP")}</span>
              </div>
              <div className="flex items-center justify-between">
                <span className="text-muted-foreground flex items-center gap-2"><Tag className="h-4 w-4"/>Category</span>
                <span className="font-medium">{report.category}</span>
              </div>
               <div className="flex items-center justify-between">
                <span className="text-muted-foreground flex items-center gap-2">{report.isAnonymous ? <UserX className="h-4 w-4"/> : <User className="h-4 w-4"/>}Reporter</span>
                <span className="font-medium">{report.isAnonymous ? "Anonymous" : "Identity Provided"}</span>
              </div>
            </CardContent>
          </Card>
          <Card>
            <CardHeader>
              <CardTitle>Assignee</CardTitle>
            </CardHeader>
            <CardContent>
              {report.assignee ? (
                 <div className="flex items-center space-x-4">
                    <Avatar>
                        <AvatarImage src={report.assignee.avatarUrl} alt={report.assignee.name} />
                        <AvatarFallback>{report.assignee.name.split(' ').map(n => n[0]).join('')}</AvatarFallback>
                    </Avatar>
                    <div>
                        <p className="text-sm font-medium leading-none">{report.assignee.name}</p>
                        <p className="text-sm text-muted-foreground">{report.assignee.email}</p>
                    </div>
                </div>
              ) : (
                <div className="text-sm text-muted-foreground">Unassigned</div>
              )}
              <Button variant="outline" className="w-full mt-4">
                {report.assignee ? "Change Assignee" : "Assign Case"}
              </Button>
            </CardContent>
          </Card>
        </div>
      </div>
    </div>
  );
}
